# Generated by Django 5.0.6 on 2024-07-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_otp_code_otpcode'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
